## Aluno: Gustavo Gimpel Correia Lima
## Matrícula: `201512040488`

## Avaliação - Classificação Automática de Segmentos de Imagens 

Nesta prática você irá avaliar um dataset de 1.500 segmentos de imagens. Nesse projeto, cada instancia representa um segmento de 3x3 pixels de uma imagem de algum dos seguintes elementos:

<img src="segments.png" alt="Imagens que foram seguementadas">

Assim, esta tarefa consiste em classificar tais segmentos de 3x3 pixels em um dos tipos de imagens externas (cimento, janela, grama, etc.). Cada instancia é representada da seguinte forma: 

<ol>
    <li>region-centroid-col:  média do valor dos pixels (coluna) </li>
    <li>region-centroid-row:  média do valor dos pixels (linha) </li>
    <li>region-pixel-count:  o número de pixels em uma região(3x3 = 9 neste caso) </li>
    <li>short-line-density-5: resultados de uma linha extraída no algoritmo que conta quantas linhas de comprimento 5 (qualquer orientação) com baixo contraste, menor ou igual a 5, passam pela região. </li>
    <li>short-line-density-2:  igual a densidade de linha curta-5, mas conta linhas de alto contraste, maiores que 2 </li>
    <li>vedge-mean: mede o contraste de pixels adjacentes horizontalmente na região. Existem 6, a média e o desvio padrão são dados. Este atributo é usado como um detector de borda vertical.</li>
    <li>vegde-sd: desvio padrão do contraste de pixels adjacentes horizontalmente </li>
    <li>hedge-mean: mede o contraste de pixels adjacentes verticalmente. Usado para detecção de linha horizontal. </li>
    <li>hedge-sd: desvio padrão do contraste de pixels adjacentes verticalmente.</li>
    <li>intensity-mean:  a média na região de (R + G + B) / 3 </li>
    <li>rawred-mean: a média sobre a região do valor R (cor vermelha) </li>
    <li>rawblue-mean: a média sobre a região do valor B (cor azul) </li>
    <li>rawgreen-mean: a média sobre a região do valor G (cor verde) </li>
    <li>exred-mean: mede o excesso de vermelho: (2R - (G + B)) </li>
    <li>exblue-mean: mede o excesso de azul: (2B - (G + R)) </li>
    <li>exgreen-mean: mede o excesso de verde:  (2G - (R + B)) </li>
    <li>value-mean: transformação não-linear 3-d de RGB </li>
    <li>saturatoin-mean: média de saturação do RGB</li>
    <li>hue-mean: média de tonalidade do RGB </li>
    <b><li style="color: red">y-i: classe a ser inferida (ver figura acima)</li></b>
</ol>

<a href="https://storm.cis.fordham.edu/~gweiss/data-mining/weka-data/segment-challenge.arff">**Referência**</a>

**Atividade 7 - Leitura do Dataset e criação dos folds:** Leia o dataset [`segment.csv`](segment.csv). Faça a validação cruzada de 5 partições.

In [1]:
import pandas as pd
import numpy as np
from resultado import Fold

df = pd.read_csv('segment.csv')
df.head()

region-centroid-col  region-centroid-row  region-pixel-count  \
0                   38                  189                   9   
1                   25                  199                   9   
2                   49                  139                   9   
3                   63                  220                   9   
4                  161                  135                   9   

   short-line-density-5  short-line-density-2  vedge-mean   vegde-sd  \
0                   0.0                   0.0    1.000000   0.222222   
1                   0.0                   0.0    1.111110   0.607407   
2                   0.0                   0.0    0.166667   0.077778   
3                   0.0                   0.0    3.055560  15.263000   
4                   0.0                   0.0    0.055556   0.136083   

   hedge-mean   hedge-sd  intensity-mean  rawred-mean  rawblue-mean  \
0    6.222220  33.318500       29.074100    26.333300      35.22220   
1    1.055560   0.462963       17.518500    13.111100      17.88890   
2    0.333333   0.088889        0.444444     0.000000       1.33333   
3    3.666670   6.088890        8.185190     6.555560       6.44444   
4    0.111111   0.172133        1.259260     0.777778       3.00000   

   rawgreen-mean  exred-mean  exblue-mean  exgreen-mean  value-mean  \
0        25.6667    -8.22222     18.44440     -10.22220    35.22220   
1        21.5556   -13.22220      1.11111      12.11110    21.55560   
2         0.0000    -1.33333      2.66667      -1.33333     1.33333   
3        11.5556    -4.88889     -5.22222      10.11110    11.55560   
4         0.0000    -1.44444      5.22222      -3.77778     3.00000   

   saturation-mean  hue-mean  y-i  
0         0.271208  -2.04915    5  
1         0.393002   2.69011    6  
2         0.777778  -2.09440    2  
3         0.486717   2.09315    6  
4         1.000000  -1.82221    4

In [2]:
k = 5
seed = 1
num_repeticoes = 1
num_folds_validacao = 3
num_repeticoes_validacao = 2

folds = Fold.gerar_k_folds(df, k, "y-i", num_repeticoes, seed, num_folds_validacao, num_repeticoes_validacao)
folds

[Treino: 
       region-centroid-col  region-centroid-row  region-pixel-count  \
 73                    226                  141                   9   
 701                    27                   50                   9   
 1307                   63                   13                   9   
 556                    58                  109                   9   
 785                   229                  124                   9   
 ...                   ...                  ...                 ...   
 715                    92                   56                   9   
 905                    81                   67                   9   
 1096                  104                  137                   9   
 235                    36                  207                   9   
 1061                   87                  196                   9   
 
       short-line-density-5  short-line-density-2  vedge-mean  vegde-sd  \
 73                0.000000                   0.0    0.500000

**Atividade 8 - Variação de parametros e exibição e analise de resultados: ** Aplique, pelo menos, os métodos RandomForest e Árvore de Decisão no problema variando os parametros (no mínimo, da mesma forma que foi variado na Parte 2). Apresente os resultados faça uma analise e responda, pelo menos: quais são as classes mais dificieis/fácieis de prever? Quais se confundem mais? Qual é o melhor método de classificação? Quais são os melhores parametros para cada método de aprendizado de máquina?

Para fazer a análise por classe, use as predições de todos os folds (apenas uma repetição) e gere a matriz de confusão. Qualquer dúvida, veja a aula sobre avaliação de métodos de aprendizado de máquina. A classe Resultado implementa essa matriz. 

In [3]:
from avaliacao import Experimento, OtimizacaoObjetivoRandomForest, OtimizacaoObjetivoArvoreDecisao
from metodo import ScikitLearnAprendizadoDeMaquina
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import optuna

rfc = RandomForestClassifier(random_state=1)
ml_method = ScikitLearnAprendizadoDeMaquina(rfc)
exp_rfc = Experimento(folds,ml_method, OtimizacaoObjetivoRandomForest, num_trials=10,
                    sampler=optuna.samplers.TPESampler(seed=1, n_startup_trials=3))

dtree = DecisionTreeClassifier(random_state=1)
ml_method = ScikitLearnAprendizadoDeMaquina(dtree)
exp_dtree = Experimento(folds, ml_method, OtimizacaoObjetivoArvoreDecisao, num_trials=10,
                    sampler=optuna.samplers.TPESampler(seed=1, n_startup_trials=3))

results_rfc = exp_rfc.calcula_resultados()
results_dtree = exp_dtree.calcula_resultados()

[I 2021-03-15 01:43:16,416] A new study created in memory with name: no-name-23ed4b52-3f56-4269-a5fe-ebf31a1dea3a
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resul

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 3 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 0 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 3 precisão foi definida como zero.
  

[I 2021-03-15 01:43:17,172] A new study created in memory with name: no-name-cf1721a9-2ebf-45c1-9200-ebca2df6c760
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
[I 2021-03-15 01:43:17,244] Trial 0 finished with value: 0.8139890042960084 and parameters: {'min_samples_split': 0.1983837371153349

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
[I 2021-03-15 01:43:17,601] Trial 6 finished with value: 0.8178705556849203 and parameters: {'min_samples_split': 0.19253905954248632, 'max_features': 0.31248197927333554, 'num_arvores': 2}. Best is trial 2 with value: 0.9318951768359015.
/home/j

[I 2021-03-15 01:43:17,744] Trial 8 finished with value: 0.9204759682668686 and parameters: {'min_samples_split': 0.07896687630058774, 'max_features': 0.36523203120740644, 'num_arvores': 2}. Best is trial 2 with value: 0.9318951768359015.
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/j

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 2 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 3 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  

[I 2021-03-15 01:43:18,110] Trial 3 finished with value: 0.9309914747958121 and parameters: {'min_samples_split': 0.06776424995451669, 'max_features': 0.49456608736517327, 'num_arvores': 4}. Best is trial 3 with value: 0.9309914747958121.
[I 2021-03-15 01:43:18,215] Trial 4 finished with value: 0.9491273560051031 and parameters: {'min_samples_split': 0.009035046843659397, 'max_features': 0.3150327725881246, 'num_arvores': 5}. Best is trial 4 with value: 0.9491273560051031.
[I 2021-03-15 01:43:18,312] Trial 5 finished with value: 0.9504721499459289 and parameters: {'min_samples_split': 0.008352209808666577, 'max_features': 0.286630507433499, 'num_arvores': 5}. Best is trial 5 with value: 0.9504721499459289.
[I 2021-03-15 01:43:18,397] Trial 6 finished with value: 0.8405942575814908 and parameters: {'min_samples_split': 0.17739590526823545, 'max_features': 0.272412606828776, 'num_arvores': 5}. Best is trial 5 with value: 0.9504721499459289.
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 3 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
[I 2021-03-15 01:43:18,603] Trial 9 finished with value: 0.5658721178559515 and parameters: {'min_samples_split': 0.3266313000756864, 'max_features': 0.3734657295251613, 'num_arvores': 3}. Best is trial 5 with value: 0.9504721499459289.
[I 2021-03-15 01:43:18,624] A new study created in memory with name: no-name-aacbae56-e2b1-4af9-8394-2c8d42fea632
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elem

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 0 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 2 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 0 precisão foi definida como zero.
  

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 2 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 2 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 3 precisão foi definida como zero.
  

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 2 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
[I 2021-03-15 01:43:19,611] Trial 2 finished with value: 0.6492072966148313 and parameters: {'min_samples_split': 0.37507215747248374, 'max_features': 0.49443054445324736, 'num_arvores': 5}. Best is trial 2 with value: 0.6492072966148313.
[I 2021-03-15 01:43:19,656] Trial 3 finished with value: 0.9200412719651672 and parameters: {'min_samples_split': 0.0035594903565914215, 'max_features': 0.48328298968540606, 'num_arvores': 1}. Best is trial 3 with value: 0.9200412719651672.
[I 2021-03-15 01:43:19,701] Trial 4 finished with value: 0.9209235783742065 and parameters: {'min_samples_split': 0.007528021863531437, 'max_fe

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 3 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 0 precisão foi definida como zero.
  

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 3 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 2 precisão foi definida como zero.
  

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
[I 2021-03-15 01:43:20,890] Trial 6 finished with value: 0.756530246840173 and parameters: {'min_samples_split': 0.2591267571201924}. Best is trial 5 with value: 0.93840452088298.
[I 2021-03-15 01:43:20,947] Trial 7 finished with value: 0.9336436446965891 and parameters: {'min_samples_split': 0.002845525714340047}. Best is trial 5 with value: 0.93840452088298.
[I 2021-03-15 01:43:20,994] Trial 8 finished with value: 0.8450113791236907 and parameters: {'min_samples_split': 0.21694833384062095}. Best is trial 5 with value: 0.93840452088298.
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRE

[I 2021-03-15 01:43:21,356] Trial 5 finished with value: 0.9398739896017635 and parameters: {'min_samples_split': 0.004700275746641974}. Best is trial 5 with value: 0.9398739896017635.
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 2 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM 

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  

[I 2021-03-15 01:43:21,763] Trial 3 finished with value: 0.933965752100708 and parameters: {'min_samples_split': 0.023278261601443057}. Best is trial 3 with value: 0.933965752100708.
[I 2021-03-15 01:43:21,818] Trial 4 finished with value: 0.9419213498907366 and parameters: {'min_samples_split': 0.0021864179388490293}. Best is trial 4 with value: 0.9419213498907366.
[I 2021-03-15 01:43:21,874] Trial 5 finished with value: 0.9289757960208264 and parameters: {'min_samples_split': 0.03841816065905437}. Best is trial 4 with value: 0.9419213498907366.
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 0 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMO

/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 0 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 2 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 6 precisão foi definida como zero.
  

[I 2021-03-15 01:43:22,460] Trial 6 finished with value: 0.9366615361655778 and parameters: {'min_samples_split': 0.00800709257599233}. Best is trial 2 with value: 0.9368836113364974.
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM ALGORITMOS - APRENDIZADO DE MÁQUINA/Prática 3 - Avaliação/Parte 3/resultado.py:72: UndefinedMetricWarning: Não há elementos previstos para a classe 4 precisão foi definida como zero.
  warnings.warn("Não há elementos previstos para a classe "+str(classe)+" precisão foi definida como zero.", UndefinedMetricWarning)
/home/jovyan/work/notebooks/DECOM.199 - TÓPICOS ESPECIAIS EM A

In [5]:
print("Resultados para RandomForestClassifier: \n")

fold_num = 0
melhor_resultado = None
melhores_parametros = None
arr_macrof1_rfc = []
arr_acuracia_rfc = []
for resultado in results_rfc:
    fold_num += 1
    print("--------------------------------------------------------------------------------- \n")
    print("[" +str(fold_num)+"]: " + str(exp_rfc.studies_per_fold[fold_num-1].best_params))
    print(resultado.mat_confusao)
    arr_macrof1_rfc.append(resultado.macro_f1)
    arr_acuracia_rfc.append(resultado.acuracia)
    print("Acurácia: " + str(resultado.acuracia))
    print("Macro_F1: " + str(resultado.macro_f1) + "\n")
    if(melhor_resultado == None or melhor_resultado.macro_f1 < resultado.macro_f1):
        melhor_resultado = resultado
        melhores_parametros = exp_rfc.studies_per_fold[fold_num-1].best_params
    
print("--------------------------------------------------------------------------------- \n")
print(">>> Média da Acurácia: " + str(exp_rfc.acuracia_avg))
print(">>> Desvio Padrão da Acurácia: " + str(np.std(arr_acuracia_rfc)) + "\n")

print(">>> Média da MacroF1: " + str(exp_rfc.macro_f1_avg))
print(">>> Desvio Padrão da MacroF1: " + str(np.std(arr_macrof1_rfc)) + "\n")

print("Melhores Parâmetros:" + str(melhores_parametros))

Resultados para RandomForestClassifier: 

--------------------------------------------------------------------------------- 

[1]: {'min_samples_split': 0.00814129553825832, 'max_features': 0.49823597966566446, 'num_arvores': 3}
[[35.  0.  0.  1.  0.  0.  0.]
 [ 0. 53.  0.  0.  0.  0.  0.]
 [ 1.  0. 31.  0.  4.  0.  0.]
 [ 1.  0.  1. 47.  3.  0.  0.]
 [ 1.  0.  1.  0. 35.  0.  0.]
 [ 0.  0.  0.  0.  0. 53.  0.]
 [ 0.  0.  0.  0.  0.  0. 33.]]
Acurácia: 0.9566666666666667
Macro_F1: 0.9529389457072451

--------------------------------------------------------------------------------- 

[2]: {'min_samples_split': 0.013693796598963082, 'max_features': 0.3352337550892011, 'num_arvores': 2}
[[41.  0.  0.  0.  0.  0.  0.]
 [ 0. 47.  0.  0.  0.  0.  0.]
 [ 0.  0. 36.  3.  6.  0.  0.]
 [ 1.  0.  0. 27.  1.  0.  0.]
 [ 2.  0.  8.  8. 34.  0.  0.]
 [ 0.  0.  0.  3.  0. 46.  0.]
 [ 0.  0.  0.  1.  0.  0. 36.]]
Acurácia: 0.89
Macro_F1: 0.8885947492675849

--------------------------------------------

In [6]:
print("Resultados para DecisionTreeClassifier: \n")

fold_num = 0
melhor_resultado = None
melhores_parametros = None
arr_macrof1 = []
arr_acuracia = []
for resultado in results_dtree:
    fold_num += 1
    print("--------------------------------------------------------------------------------- \n")
    print("[" +str(fold_num)+"]: " + str(exp_dtree.studies_per_fold[fold_num-1].best_params))
    print(resultado.mat_confusao)
    arr_macrof1.append(resultado.macro_f1)
    arr_acuracia.append(resultado.acuracia)
    print("Acurácia: " + str(resultado.acuracia))
    print("Macro_F1: " + str(resultado.macro_f1) + "\n")
    if(melhor_resultado == None or melhor_resultado.macro_f1 < resultado.macro_f1):
        melhor_resultado = resultado
        melhores_parametros = exp_dtree.studies_per_fold[fold_num-1].best_params

print("--------------------------------------------------------------------------------- \n")
print(">>> Média da Acurácia: " + str(exp_dtree.acuracia_avg))
print(">>> Desvio Padrão da Acurácia: " + str(np.std(arr_acuracia)) + "\n")

print(">>> Média da MacroF1: " + str(exp_dtree.macro_f1_avg))
print(">>> Desvio Padrão da MacroF1: " + str(np.std(arr_macrof1)) + "\n")

print("Melhores Parâmetros:" + str(melhores_parametros))

Resultados para DecisionTreeClassifier: 

--------------------------------------------------------------------------------- 

[1]: {'min_samples_split': 0.009897162413044502}
[[36.  0.  0.  0.  0.  0.  0.]
 [ 0. 53.  0.  0.  0.  0.  0.]
 [ 2.  0. 32.  0.  2.  0.  0.]
 [ 0.  0.  1. 50.  1.  0.  0.]
 [ 0.  0.  1.  1. 35.  0.  0.]
 [ 0.  0.  0.  0.  0. 53.  0.]
 [ 0.  0.  0.  0.  0.  0. 33.]]
Acurácia: 0.9733333333333334
Macro_F1: 0.9702094009999697

--------------------------------------------------------------------------------- 

[2]: {'min_samples_split': 0.008212475466642548}
[[40.  0.  0.  0.  1.  0.  0.]
 [ 0. 47.  0.  0.  0.  0.  0.]
 [ 0.  0. 43.  1.  1.  0.  0.]
 [ 0.  0.  0. 27.  2.  0.  0.]
 [ 0.  0.  7.  5. 40.  0.  0.]
 [ 0.  0.  2.  1.  0. 46.  0.]
 [ 0.  0.  0.  0.  0.  0. 37.]]
Acurácia: 0.9333333333333333
Macro_F1: 0.9333070717485362

--------------------------------------------------------------------------------- 

[3]: {'min_samples_split': 0.004700275746641974}
[[36.

# `Como o melhor estudo do optuna utiliza a macrof1 como objetivo, a análise será feita somente com base na macrof1.`

## Analisando as matrizes de confusão e as métricas, é possível observar que o desvio padrão da MacroF1 da DecisionTree foi menor (0.018351995449227672) se comparado com o desvio padrão da MacroF1 da RandomForest (0.02523660062177899), o que indica que a DecisionTree foi mais consistente, visto que as variações na MacroF1 foram menores.

## Nenhum dos dois métodos foi melhor que o outro em todos os folds, porém, a média das MacroF1s dos resultados foi ligeiramente superior na DecisionTree. Contudo, deve ser avaliada uma margem de erro, visto que a diferença foi aproximadamente 0.0046.

## Os melhores parâmetros de cada método foram:
`DecisionTree: 'min_samples_split': 0.009897162413044502
RandomForest: 'min_samples_split': 0.007425741658307137, 'max_features': 0.3092744544619145, 'num_arvores': 4`

## Analisando as matrizes de confusão, é possível observar também que as classes 3, 4 e 5 foram as mais difíceis de serem previstas, visto que o número de erros é normalmente maior do que nas classes 1, 2, 6 e 7. As classes 3, 4 e 5 foram as que mais geraram confusão, visto que houveram várias predições trocadas entre elas.

# `O melhor método de classificação, portanto, foi o DecisionTreeClassifier`